#! /bin/sh

# Allows for colors and such
export TERM=xterm-256color

# Start from the repository root
cd ./$(git rev-parse --show-cdup)

# Delete .pyc files and empty directories
printf "\e[32mRemoving .pyc and empty directories...\n\033[0m"
find . -name "*.pyc" -delete
find . -type d -empty -delete

.git/hooks/ctags > /dev/null 2>&1 
